name: lung_cancer_detection
channels:
  - conda-forge
  - pytorch
dependencies:
  - python=3.9
  - black
  - flake8
  - isort
  - pip
  - typer
  - loguru
  - tqdm
  - ipython
  - matplotlib
  - numpy
  - pandas
  - seaborn
  - scikit-learn
  - tensorflow 
  - keras
  - datasets
  - transformers
  - evaluate
  - pillow

  - pip:
      - python-dotenv
      - kaggle
